version: '3'

services:
  element-app:
    build: Frontend/.
    container_name: element-app
    restart: always
    ports:
      - 8000:80
    networks:
      - element-network
    volumes:
      - ./Frontend/src:/app
    depends_on:
      - element-db
  element-db:
    build: backend/.
    container_name: element-db
    restart: always
    ports:
      - 3306:3306
    networks:
      - element-network

networks:
  element-network: